version: "3"
services:
  install:
    # user: node
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && rm -rf node_modules && rm -rf yarn.lock && yarn install"
  build: 
    # user: node
    image: node:18.15
    volumes:
      - .:/app
    command: bash -c "cd /app && yarn build"